# Generated by Django 4.2.7 on 2023-11-16 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='total_likes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name='images',
            index=models.Index(fields=['-total_likes'], name='images_imag_total_l_6fd6e6_idx'),
        ),
    ]
